### ISSUE TITLE
Actualización Documentación

### ISSUE THREAD

**Issue by fbaroni** [deimsantafe/bundle-stg-theme-bundle#1]
- En config.yml falta "materialize"
- En SF 3.4 no anda la opción form dentro de twig
- En Symfony 3.4 para extender el tema definirlo. {% extends '@STGTheme/Default/base.html.twig' %}
- Sacar dev del require

**Comment by lucasaguilar** [comment]
Documentación actualizada en: https://github.com/deimsantafe/bundle-stg-theme-bundle/tree/2.x

**Comment by lucasaguilar** [comment]
Para utilizar el tema de materializecss:

{% extends 'STGThemeBundle:Default:baseMaterializecss.html.twig' %}

en Symfony >= 3.4

{% extends '@STGTheme/Default/baseMaterializecss.html.twig' %}

Se agrego en la documentción del bundle.-
